SecAction \
    "id:10000,\
     phase:1,\
     pass,\
     nolog,\
     t:none,\
     ver:'LAB/1.0',\
     setvar:tx.blocking_paranoia_level=1,\
     setvar:tx.detection_paranoia_level=1"

SecAction \
    "id:10001,\
     phase:1,\
     pass,\
     nolog,\
     t:none,\
     ver:'LAB/1.0',\
     setvar:tx.inbound_anomaly_score_threshold=5,\
     setvar:tx.outbound_anomaly_score_threshold=4"

SecAction \
    "id:10002,\
     phase:1,\
     pass,\
     nolog,\
     t:none,\
     ver:'LAB/1.0',\
     setvar:tx.reporting_level=4"
