SecRuleEngine On

SecRequestBodyAccess On
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 131072
SecRequestBodyLimitAction Reject
SecRequestBodyJsonDepthLimit 512
SecArgumentsLimit 1000

SecResponseBodyAccess On
SecResponseBodyMimeType text/plain text/html text/xml application/json
SecResponseBodyLimit 524288
SecResponseBodyLimitAction ProcessPartial

SecPcreMatchLimit 100000
SecPcreMatchLimitRecursion 100000

SecTmpDir /tmp/
SecDataDir /tmp/
SecUploadDir /tmp/
SecUploadKeepFiles Off
SecUploadFileMode 0600

SecAuditEngine On
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABCEFHZ
SecAuditLogType Serial
SecAuditLogFormat JSON
SecAuditLog /var/log/modsec/audit.log

SecDebugLog /var/log/modsec/debug.log
SecDebugLogLevel 0

SecUnicodeMapFile /etc/nginx/unicode.mapping 20127
SecStatusEngine Off

SecRule REQUEST_HEADERS:Content-Type "^(?:application(?:/soap\\+|/)|text/)xml" \
    "id:200000,\
     phase:1,\
     pass,\
     nolog,\
     t:none,t:lowercase,\
     ctl:requestBodyProcessor=XML"

SecRule REQUEST_HEADERS:Content-Type "^application/json" \
    "id:200001,\
     phase:1,\
     pass,\
     nolog,\
     t:none,t:lowercase,\
     ctl:requestBodyProcessor=JSON"

SecRule REQUEST_HEADERS:Content-Type "^application/[a-z0-9.-]+[+]json" \
    "id:200006,\
     phase:1,\
     pass,\
     nolog,\
     t:none,t:lowercase,\
     ctl:requestBodyProcessor=JSON"

SecRule REQBODY_ERROR "!@eq 0" \
    "id:200002,\
     phase:2,\
     deny,\
     status:400,\
     log,\
     t:none,\
     msg:'Failed to parse request body',\
     logdata:'%{reqbody_error_msg}',\
     severity:2"

SecRule MULTIPART_STRICT_ERROR "!@eq 0" \
    "id:200003,\
     phase:2,\
     deny,\
     status:400,\
     log,\
     t:none,\
     msg:'Multipart request body failed strict validation',\
     logdata:'REQBODY_ERROR=%{REQBODY_ERROR}, MULTIPART_STRICT_ERROR=%{MULTIPART_STRICT_ERROR}'"

SecRule MULTIPART_UNMATCHED_BOUNDARY "@eq 1" \
    "id:200004,\
     phase:2,\
     deny,\
     status:400,\
     log,\
     t:none,\
     msg:'Multipart parser detected a possible unmatched boundary'"

SecRule TX:/^MSC_/ "!@streq 0" \
    "id:200005,\
     phase:2,\
     deny,\
     log,\
     t:none,\
     msg:'ModSecurity internal error flagged: %{MATCHED_VAR_NAME}'"

SecRule &ARGS "@ge 1000" \
    "id:200007,\
     phase:2,\
     deny,\
     status:400,\
     log,\
     t:none,\
     msg:'Failed to fully parse request body due to large argument count',\
     severity:2"
