#!/usr/sbin/nft -f

flush ruleset

define WAN_IF = "ens33"
define LAN_IF = "ens36"
define LAN_NET = 192.168.130.0/24

table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;

		iif "lo" accept
		ct state established,related accept
		ct state invalid drop

		ip protocol icmp accept
		ip6 nexthdr ipv6-icmp accept

		tcp dport 22 accept
		iifname $WAN_IF tcp dport 80 accept
	}

	chain forward {
		type filter hook forward priority filter; policy drop;

		ct state established,related accept
		ct state invalid drop

		iifname $LAN_IF oifname $WAN_IF accept

		iifname $WAN_IF oifname $LAN_IF log prefix "nft-drop-wan2lan " drop
	}

	chain output {
		type filter hook output priority filter; policy accept;
	}
}

table ip nat {
	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;

		ip saddr $LAN_NET oifname $WAN_IF masquerade
	}
}
