server {
    listen 127.0.0.1:3000;
    server_name stub-origin;

    default_type application/json;

    location = /rest/products/reviews {
        return 401 '{"error":"Unauthorized"}';
    }

    location /api/BasketItems/ {
        return 401 '{"error":"Unauthorized"}';
    }

    location /rest/user/change-password {
        return 500 '{"error":"Blocked illegal activity"}';
    }

    location / {
        return 200 '{"stub":"origin"}';
    }
}
